FROM opensuse:harlequin
MAINTAINER tedgin@cyverse.org

RUN zypper --non-interactive remove krb5-mini
RUN zypper --non-interactive install \
    curl fuse-devel gcc-c++ help2man krb5-devel libbz2-devel libcurl-devel libopenssl-devel libxml2-devel \
    make pam-devel perl-JSON python python-devel rpm-build rsync unixODBC wget zlib-devel
RUN mkdir /rpmbuild /src
RUN chmod a+w /rpmbuild

VOLUME /src

WORKDIR /src

CMD bash

